apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv
  template:
    metadata:
      labels:
        app: cv
    spec:
      containers:
      - name: cv-container
        image: mohammadalkhatib97/project-cv1:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  selector:
    app: cv
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

